title: Chris Kucewicz # your name (or website title) here
logo: "https://raw.githubusercontent.com/ckucewicz21/ckucewicz21.github.io/main/Screen%20Shot%202022-09-21%20at%2010.09.18%20PM.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, my name is Chris. I hold a B.S. in Mathematics from the University of Pittsburgh. Currently, I am in my 3rd year working as a high school math teacher, but I am in the process of transitioning into the data analytics/science field.
  
  
  <br><br>
  I have been teaching myself how to code through online courses and additional resources ("Analyzing Baseball Data in R" by Jim Albert and Max Marchi; and "Intro to Statistical Learning with Applications in R", Springer Texts in Statistics). Right now, I'm learning Python through Codecademy's Data Scientist: Machine Learning Specialist online program.  
  <br><br>

  
#theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
